sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=locked
    - php: 5.6
      env:
        - DEPS=lastest
    - php: 7.0
      env:
        - DEPS=lowest
    - php: 7.0
      env:
        - EXECUTE_CS_CHECK=true
        - EXECUTE_COVERAGE=true
        - DEPS=locked
    - php: 7.0
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=locked
    - php: 7.1
      env:
        - DEPS=latest
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.2
      env:
        - DEPS=latest
    - php: nightly
      env:
        - DEPS=lowest
    - php: nightly
      env:
        - DEPS=latest
  allow_failures:
    - php: nightly

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS

script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then travis_retry wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then travis_retry php ocular.phar code-coverage:upload --format=php-clover clover.xml ; fi
