sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env:
        - DEPS=lowest
    - php: 7.4
      env:
        - DEPS=locked
    - php: 7.4
      env:
        - DEPS=latest
    - php: nightly
      env:
        - DEPS=lowest
    - php: nightly
      env:
        - DEPS=latest
  allow_failures:
    - php: nightly

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS

script:
  - if [[ $DEPS == 'locked' ]]; then ./vendor/bin/phpstan analyze ; fi
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; else ./vendor/bin/phpunit ; fi

after_script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then travis_retry wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then travis_retry php ocular.phar code-coverage:upload --format=php-clover clover.xml ; fi
